#!/bin/bash
#
# Runs RPNCalc as a bash script with the needed options
#
exec "$SNAP"/bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -Dorg.jline.terminal.dumb=true -jar "$SNAP"/jar/rpncalc.jar "$@"
