name: rpncalc
version: '5.0.2'
summary: The command line Reverse Polish Notation (RPN) calculator
description: |
  RPNCalc is an easy to use command line based Reverse Polish
  Notation (RPN) calculator.
  
  RPN calculators make it very simple to do complex calculations, especially
  if there are parentheses involved or order of operations is imporant. Take a look
  at the user guide for more information on RPN Calculators.
  
  For a quick summary of RPNCalc usage, run the program with the -h switch or head
  over to the User Guide for detailed usage instructions.
  
  Homepage: https://github.com/frossm/rpncalc
  RPNCalc user guide: https://frossm.github.io/RPNCalc-UserGuide

grade: stable
confinement: strict
base: core18

title: RPNCalc
website: https://github.com/frossm/rpncalc
contact: rpncalc@fross.org
issues: https://github.com/frossm/rpncalc/issues
icon: graphics/PostIt-512x512.png
license: MIT


# Enable faster LZO compression
compression: lzo

apps:
   rpncalc:
      command: rpncalc-wrapper
      plugs:
         - network

parts:
   wrapper:
      plugin: dump
      source: snap/local
      source-type: local
    
   library:
      plugin: maven
      source: https://github.com/frossm/library.git
      source-type: git
      source-tag: 'v2023.05.21'
      maven-options: [install]

   rpncalc:
      plugin: maven
      source: https://github.com/frossm/rpncalc.git
      source-branch: master
      source-type: git
      after:
         - library
         - wrapper

      # Bypass a build issue where an absolute reference is made to a file outside of the snap filesystem 
      # Ref: https://forum.snapcraft.io/t/resolve-package-contains-external-symlinks-error-when-trying-to-snap/2963/23
      override-prime: |
         snapcraftctl prime
         rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
