name: rpncalc
title: RPNCalc
version: '6.0.6'
summary: The command-line Reverse Polish Notation (RPN) calculator
description: |
  RPNCalc is the command-line based Reverse Polish Notation (RPN) calculator. 
  RPN calculators make it very simple to do complex calculations, especially
  if there are parentheses involved. In essence, you enter your numbers first,
  and then the operator.
  
  So, to add 2 and 3 to get 5, you would first add the number 2 to the stack.
  Then you would add 5 to the stack (pushing the 2 to the second position.)
  Now, to add them you would enter + and RPNCalc would remove the 2 and 3 
  from the stack, add them, and push 5 back onto the stack.
  
  There is a very large collection of functions that can be used.  Trig functions,
  statistical functions, user defined functions, multiple stacks, constants, etc. 
  
  For a quick summary of RPNCalc usage, run the program with the -h switch or enter `h` 
  within the program.
  
  Please take a look at the User guide for detailed information on what 
  RPNCalc is and how to use it. Once you use an RPN calculator, 
  it's hard to go back to a traditional one.
  
  Homepage: https://github.com/frossm/rpncalc
  RPNCalc user guide: https://frossm.github.io/RPNCalc-UserGuide

grade: stable
confinement: strict
base: core24
type: app

website: https://github.com/frossm/rpncalc
contact: rpncalc@fross.org
issues: https://github.com/frossm/rpncalc/issues
icon: graphics/PostIt.svg
license: MIT

platforms:
  amd64:
  arm64:
  armhf:
#  s390x:
#  ppc64el:

# Enable faster LZO decompression
compression: lzo

apps:
   rpncalc:
      command: rpncalc-wrapper
      environment:
        PATH: $SNAP/usr/lib/jvm/java-21-openjdk-amd64/bin:$PATH
        JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64

      plugs:
         - network
         - home

parts:
  rpncalc:
    plugin: nil
    source: .
    build-attributes: [network]

    override-build: |
      # Ensure that gradlew is executable
      chmod +x gradlew
      
      # Build the application
      ./gradlew shadowJar -x test --console=plain
      
      # Move the shadowJar to the right place
      mkdir -p $SNAPCRAFT_PART_INSTALL/jar
      cp build/libs/*.jar $SNAPCRAFT_PART_INSTALL/jar/rpncalc.jar
      
      # Move the wrapper and ensure it's executable
      cp $SNAPCRAFT_PROJECT_DIR/snap/local/rpncalc-wrapper $SNAPCRAFT_PART_INSTALL/
      chmod +x $SNAPCRAFT_PART_INSTALL/rpncalc-wrapper

    build-packages:
      - gradle
      - openjdk-21-jdk-headless

    stage-packages:
      - openjdk-21-jre-headless

